name = 'edgetunnel'
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true
[vars]
ADMIN = "renren"
[[kv_namespaces]]
binding = "KV"
id = "89804af050c34642acd23977da2e85e1"

#[[kv_namespaces]]
#binding = "KV"			#KV绑定名默认不可修改
#id = ""				#KV数据库id
